set_property SRC_FILE_INFO {cfile:C:/Vivaldo/Lab1/Lab1_Question4/Lab1_Question4.srcs/constrs_1/new/logic_gate.xdc rfile:../../../Lab1_Question4.srcs/constrs_1/new/logic_gate.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports E]; set_property IOSTANDARD LVCMOS33 [get_ports E]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports D]; set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports C]; set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports B]; set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports A]; set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports F]; set_property IOSTANDARD LVCMOS33 [get_ports F]
