set_property SRC_FILE_INFO {cfile:C:/Vivaldo/Lab1/Lab1_Question3/Lab1_Question3.srcs/constrs_1/new/basys3_adder_substracter.xdc rfile:../../../Lab1_Question3.srcs/constrs_1/new/basys3_adder_substracter.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports B0]; set_property IOSTANDARD LVCMOS33 [get_ports B0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports B1]; set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports B2]; set_property IOSTANDARD LVCMOS33 [get_ports B2]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports B3]; set_property IOSTANDARD LVCMOS33 [get_ports B3]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports A0]; set_property IOSTANDARD LVCMOS33 [get_ports A0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports A1]; set_property IOSTANDARD LVCMOS33 [get_ports A1]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports A2]; set_property IOSTANDARD LVCMOS33 [get_ports A2]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports A3]; set_property IOSTANDARD LVCMOS33 [get_ports A3]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports C]; set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports S0]; set_property IOSTANDARD LVCMOS33 [get_ports S0]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports S1]; set_property IOSTANDARD LVCMOS33 [get_ports S1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports S2]; set_property IOSTANDARD LVCMOS33 [get_ports S2]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports S3]; set_property IOSTANDARD LVCMOS33 [get_ports S3]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports Cout]; set_property IOSTANDARD LVCMOS33 [get_ports Cout]
