set_property SRC_FILE_INFO {cfile:C:/Vivaldo/Lab1/Lab1_Question2/Lab1_Question2.srcs/constrs_1/new/basys3_decoder.xdc rfile:../../../Lab1_Question2.srcs/constrs_1/new/basys3_decoder.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports A0]; set_property IOSTANDARD LVCMOS33 [get_ports A0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports A1]; set_property IOSTANDARD LVCMOS33 [get_ports A1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports A2]; set_property IOSTANDARD LVCMOS33 [get_ports A2]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports E]; set_property IOSTANDARD LVCMOS33 [get_ports E]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Y0]; set_property IOSTANDARD LVCMOS33 [get_ports Y0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports Y1]; set_property IOSTANDARD LVCMOS33 [get_ports Y1]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports Y2]; set_property IOSTANDARD LVCMOS33 [get_ports Y2]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports Y3]; set_property IOSTANDARD LVCMOS33 [get_ports Y3]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports Y4]; set_property IOSTANDARD LVCMOS33 [get_ports Y4]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports Y5]; set_property IOSTANDARD LVCMOS33 [get_ports Y5]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports Y6]; set_property IOSTANDARD LVCMOS33 [get_ports Y6]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports Y7]; set_property IOSTANDARD LVCMOS33 [get_ports Y7]
