set_property SRC_FILE_INFO {cfile:C:/Vivaldo/Lab1/Lab1_Question1/Lab1_Question1.srcs/constrs_1/new/basys3_mux.xdc rfile:../../../Lab1_Question1.srcs/constrs_1/new/basys3_mux.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports D0]; set_property IOSTANDARD LVCMOS33 [get_ports D0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports D1]; set_property IOSTANDARD LVCMOS33 [get_ports D1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports D2]; set_property IOSTANDARD LVCMOS33 [get_ports D2]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports D3]; set_property IOSTANDARD LVCMOS33 [get_ports D3]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports D4]; set_property IOSTANDARD LVCMOS33 [get_ports D4]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports D5]; set_property IOSTANDARD LVCMOS33 [get_ports D5]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports D6]; set_property IOSTANDARD LVCMOS33 [get_ports D6]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports D7]; set_property IOSTANDARD LVCMOS33 [get_ports D7]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2  [get_ports D8]; set_property IOSTANDARD LVCMOS33 [get_ports D8]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3  [get_ports D9]; set_property IOSTANDARD LVCMOS33 [get_ports D9]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T2  [get_ports D10]; set_property IOSTANDARD LVCMOS33 [get_ports D10]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3  [get_ports D11]; set_property IOSTANDARD LVCMOS33 [get_ports D11]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W2  [get_ports D12]; set_property IOSTANDARD LVCMOS33 [get_ports D12]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1  [get_ports D13]; set_property IOSTANDARD LVCMOS33 [get_ports D13]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1  [get_ports D14]; set_property IOSTANDARD LVCMOS33 [get_ports D14]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2  [get_ports D15]; set_property IOSTANDARD LVCMOS33 [get_ports D15]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports S0]; set_property IOSTANDARD LVCMOS33 [get_ports S0]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports S1]; set_property IOSTANDARD LVCMOS33 [get_ports S1]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports S2]; set_property IOSTANDARD LVCMOS33 [get_ports S2]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports S3]; set_property IOSTANDARD LVCMOS33 [get_ports S3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Y_out]; set_property IOSTANDARD LVCMOS33 [get_ports Y_out]
